### ISSUE TITLE
'referrals' parameter does not work properly

### ISSUE THREAD

**Issue by wfsaxton** [bodgit/puppet-openldap#42]
Running latest version of puppet on Oracle Linux 7.2.

```
class { 'openldap':
    notify => Service['autofs'],
    referrals => false,
    tls_reqcert => 'never',
    uri => ['ldap://cr-lc-sca-01.example.com/', 'ldap://cr-lc-sca-02.example.com/'],
    base => 'dc=example,dc=com',
    tls_cacertdir => '/etc/openldap/cacerts'
}
```

produces

```
# !!! Managed by Puppet !!!

URI                             ldap://cr-lc-sca-01.example.com/ ldap://cr-lc-sca-02.example.com/
BASE                            dc=example,dc=com
TLS_CACERTDIR                   /etc/openldap/cacerts
TLS_REQCERT                     never
```

Setting "referrals => true" produces

```
# !!! Managed by Puppet !!!

BASE                            dc=example,dc=com
REFERRALS                       on
TLS_CACERTDIR                   /etc/openldap/cacerts
TLS_REQCERT                     never
```

Since the default behavior is "on" there is no way off turning referrals "off" with this module.

**Comment by wfsaxton** [comment]
Not a ruby expert, but I think in ldap.conf.erb:

    <% if @referrals -%> 

should be something like:

    <% if defined?(@referrals) -%>

**Comment by bodgit** [comment]
Good catch. The pattern I've used elsewhere in other templates is:
```
<% unless @referrals.nil? -%>
```
That means it only processes the block if `@referrals` is not `undef` rather than testing the "truthiness" of it.

**Comment by bodgit** [comment]
I found some more instances of the same bug in that template so I've fixed those up as well, (I guess even fewer people use this with GSSAPI). Version 1.4.1 should be up on the forge with this fixed.

Thanks for the bug report!
