### ISSUE TITLE
Add writemap et nometasync support

### ISSUE THREAD

**Issue by HerveMARTIN** [bodgit/puppet-openldap#45]
For performance reason, it's often advised to add these two flags for mdb backend : 
olcDbEnvFlags: writemap
olcDbEnvFlags: nometasync

I didn't find how to setup this with your module.
I'll look forward to propose a patch or a PR.

**Comment by bodgit** [comment]
Sorry, I've been on holiday for a couple of weeks, shouldn't be hard to add something to support this.

**Comment by bodgit** [comment]
I've added the following parameters, `accesslog_envflags` and `data_envflags` for supplying these flags. As I've been doing a lot of refactoring for a v2.0.0 release they are in that branch pending a release.

Thanks for the bug report!
