### ISSUE TITLE
Could not evaluate: undefined method `context=' for #<Augeas:0x7fe2f0297ea0>

### ISSUE THREAD

**Issue by raja5674** [bodgit/puppet-openldap#54]
Hello,
When I run my vagrant up command, getting the following error. Could you please help me to find the root cause?

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'puppetlabs/centos-6.6-64-puppet'...

[KProgress: 30%
[KProgress: 40%
[KProgress: 50%
[KProgress: 60%
[KProgress: 90%
[K==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: ifast-config
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: You are trying to forward to privileged ports (ports <= 1024). Most
==> default: operating systems restrict this to only privileged process (typically
==> default: processes running as an administrative user). This is a warning in case
==> default: the port forwarding doesn't work. If any problems occur, please try a
==> default: port higher than 1024.
==> default: Forwarding ports...
    default: 5432 (guest) => 5432 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 8443 (guest) => 8443 (host) (adapter 1)
    default: 9990 (guest) => 9990 (host) (adapter 1)
    default: 9443 (guest) => 9443 (host) (adapter 1)
    default: 389 (guest) => 389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.22
    default: VirtualBox Version: 6.0
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => D:/ICS_Workspace/ifast-config
    default: /tmp/vagrant-puppet/modules-627a278609c010fadb794c2725c1489a => D:/ICS_Workspace/ifast-config/puppet/modules
    default: /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3 => D:/ICS_Workspace/ifast-config/puppet/manifests
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: C:/Users/wp040631/AppData/Local/Temp/vagrant-shell20190430-12632-1lcp6wx.sh
    default: Installing ca-certificates
    default: Loaded plugins: fastestmirror, security
    default: Setting up Install Process
    default: Determining fastest mirrors
    default:  * base: mirror.csclub.uwaterloo.ca
    default:  * extras: mirror.csclub.uwaterloo.ca
    default:  * updates: mirror.csclub.uwaterloo.ca
    default: Resolving Dependencies
    default: --> Running transaction check
    default: ---> Package ca-certificates.noarch 0:2014.1.98-65.1.el6 will be updated
    default: ---> Package ca-certificates.noarch 0:2018.2.22-65.1.el6 will be an update
    default: --> Finished Dependency Resolution
    default: 
    default: Dependencies Resolved
    default: 
    default: ================================================================================
    default:  Package               Arch         Version                    Repository  Size
    default: ================================================================================
    default: Updating:
    default:  ca-certificates       noarch       2018.2.22-65.1.el6         base       930 k
    default: 
    default: Transaction Summary
    default: ================================================================================
    default: Upgrade       1 Package(s)
    default: Total download size: 930 k
    default: Is this ok [y/N]: Is this ok [y/N]: Exiting on user Command
==> default: Running provisioner: shell...
    default: Running: C:/Users/wp040631/AppData/Local/Temp/vagrant-shell20190430-12632-riq438.sh
    default: [mNotice: Preparing to install into /etc/puppet/modules ...[0m
    default: [mNotice: Downloading from https://forgeapi.puppetlabs.com ...[0m
    default: [mNotice: Installing -- do not interrupt ...[0m
    default: /etc/puppet/modules
    default: └─┬ puppetlabs-postgresql ([0;36mv4.7.1[0m)
    default:   ├── puppetlabs-apt ([0;36mv2.4.0[0m)
    default:   └─┬ puppetlabs-concat ([0;36mv2.2.1[0m)
    default:     └── puppetlabs-stdlib ([0;36mv4.25.1[0m)
    default: [mNotice: Preparing to install into /etc/puppet/modules ...[0m
    default: [mNotice: Downloading from https://forgeapi.puppetlabs.com ...[0m
    default: [mNotice: Installing -- do not interrupt ...[0m
    default: /etc/puppet/modules
    default: └─┬ camptocamp-openldap ([0;36mv1.14.0[0m)
    default:   └─┬ herculesteam-augeasproviders_shellvar ([0;36mv2.2.4[0m)
    default:     └─┬ herculesteam-augeasproviders_core ([0;36mv2.4.0[0m)
    default:       └── puppetlabs-stdlib ([0;36mv4.25.1[0m)
    default: [mNotice: Preparing to install into /etc/puppet/modules ...[0m
    default: [mNotice: Downloading from https://forgeapi.puppetlabs.com ...[0m
    default: [mNotice: Installing -- do not interrupt ...[0m
    default: /etc/puppet/modules
    default: └── puppetlabs-firewall ([0;36mv1.8.0[0m)
==> default: Running provisioner: puppet...
==> default: Running Puppet with site.pp...
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> default: Warning: Unrecognised escape sequence '\.' in file /tmp/vagrant-puppet/modules-627a278609c010fadb794c2725c1489a/iwd-jboss/manifests/config.pp at line 34
==> default: Warning: Unrecognised escape sequence '\.' in file /tmp/vagrant-puppet/modules-627a278609c010fadb794c2725c1489a/iwd-jboss/manifests/config.pp at line 34
==> default: 
==> default: Warning: Unrecognised escape sequence '\.' in file /tmp/vagrant-puppet/modules-627a278609c010fadb794c2725c1489a/iwd-jboss/manifests/config.pp at line 34
==> default: Warning: Unrecognised escape sequence '\1' in file /tmp/vagrant-puppet/modules-627a278609c010fadb794c2725c1489a/iwd-jboss/manifests/config.pp at line 34
==> default: Warning: Scope(Concat[/var/lib/pgsql/9.4/data/pg_ident.conf]): The $force parameter to concat is deprecated and has no effect.
==> default: Notice: Compiled catalog for target.canada01.ifdsnet.int in environment production in 5.75 seconds
==> default: Warning: The package type's allow_virtual parameter will be changing its default value from false to true in a future release. If you do not want to allow virtual packages, please explicitly set allow_virtual to false.
==> default:    (at /usr/lib/ruby/site_ruby/1.8/puppet/type/package.rb:430:in `default')
==> default: Notice: /Stage[main]/Postgresql::Repo::Yum_postgresql_org/File[/etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG-94]/ensure: defined content as '{md5}78b5db170d33f80ad5a47863a7476b22'
==> default: Notice: /Stage[main]/Openldap::Server::Install/Package[openldap-servers]/ensure: created
==> default: Notice: /Stage[main]/Postgresql::Client/File[/usr/local/bin/validate_postgresql_connection.sh]/ensure: defined content as '{md5}20301932819f035492a30880f5bf335a'
==> default: Error: /Stage[main]/Openldap::Server::Config/Shellvar[SLAPD_LDAPS]: Could not evaluate: undefined method `context=' for #<Augeas:0x7fe2f0297ea0>
==> default: Error: /Stage[main]/Openldap::Server::Config/Shellvar[SLAPD_LDAPI]: Could not evaluate: undefined method `context=' for #<Augeas:0x7fe2f0297ea0>
==> default: Notice: /Stage[main]/Iwd-migrate-db/File[/usr/share/flyway]/ensure: created
==> default: Notice: /Stage[main]/Iwd-migrate-db/Exec[download-flyway]/returns: executed successfully
==> default: Error: /Stage[main]/Openldap::Server::Config/Shellvar[SLAPD_LDAP]: Could not evaluate: undefined method `context=' for #<Augeas:0x7fe2f0297ea0>
==> default: Notice: /Stage[main]/Iwd-jdk/Exec[Install Java]/returns: executed successfully
==> default: Notice: /Stage[main]/Nexus/File[/opt/nexus-script]/ensure: created
==> default: Notice: /Stage[main]/Nexus/File[/opt/nexus-script/download-artifact-from-nexus.sh]/ensure: defined content as '{md5}3dc8a82c27d2d5512f6467f3958da8d6'
==> default: Notice: /Stage[main]/Iwd-timezone/File[/etc/localtime]/ensure: ensure changed 'file' to 'link'
==> default: Notice: /Stage[main]/Iwd-user/File[/etc/profile.d/init-alias.sh]/ensure: defined content as '{md5}0ce1c2a40d9943dd31f45bbbc84b7191'
==> default: Notice: /Stage[main]/Openldap::Server::Service/Service[slapd]: Dependency Shellvar[SLAPD_LDAPS] has failures: true
==> default: Notice: /Stage[main]/Openldap::Server::Service/Service[slapd]: Dependency Shellvar[SLAPD_LDAPI] has failures: true
==> default: Notice: /Stage[main]/Openldap::Server::Service/Service[slapd]: Dependency Shellvar[SLAPD_LDAP] has failures: true
==> default: Warning: /Stage[main]/Openldap::Server::Service/Service[slapd]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Openldap::Server::Slapdconf/File[/etc/openldap/slapd.d]: Dependency Shellvar[SLAPD_LDAPS] has failures: true
==> default: Notice: /Stage[main]/Openldap::Server::Slapdconf/File[/etc/openldap/slapd.d]: Dependency Shellvar[SLAPD_LDAPI] has failures: true
==> default: Notice: /Stage[main]/Openldap::Server::Slapdconf/File[/etc/openldap/slapd.d]: Dependency Shellvar[SLAPD_LDAP] has failures: true
==> default: Warning: /Stage[main]/Openldap::Server::Slapdconf/File[/etc/openldap/slapd.d]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Firewall::Linux::Redhat/Service[iptables]/ensure: ensure changed 'running' to 'stopped'
==> default: Notice: /Stage[main]/Openldap::Utils/Package[openldap-clients]/ensure: created
==> default: Notice: /Stage[main]/Iwd-openldap/Openldap::Server::Schema[nis]/Openldap_schema[nis]: Dependency Shellvar[SLAPD_LDAPS] has failures: true
==> default: Notice: /Stage[main]/Iwd-openldap/Openldap::Server::Schema[nis]/Openldap_schema[nis]: Dependency Shellvar[SLAPD_LDAPI] has failures: true
==> default: Notice: /Stage[main]/Iwd-openldap/Openldap::Server::Schema[nis]/Openldap_schema[nis]: Dependency Shellvar[SLAPD_LDAP] has failures: true
==> default: Notice: /Stage[main]/Iwd-openldap/Openldap::Server::Schema[cosine]/Openldap_schema[cosine]: Dependency Shellvar[SLAPD_LDAPS] has failures: true
==> default: Notice: /Stage[main]/Iwd-openldap/Openldap::Server::Schema[cosine]/Openldap_schema[cosine]: Dependency Shellvar[SLAPD_LDAPI] has failures: true
==> default: Notice: /Stage[main]/Iwd-openldap/Openldap::Server::Schema[cosine]/Openldap_schema[cosine]: Dependency Shellvar[SLAPD_LDAP] has failures: true
==> default: Warning: /Stage[main]/Iwd-openldap/Openldap::Server::Schema[nis]/Openldap_schema[nis]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Iwd-openldap/Openldap::Server::Schema[cosine]/Openldap_schema[cosine]: Skipping because of failed dependencies

Thanks,
Raja Rajagopal

**Comment by bodgit** [comment]
What OS is this and what version of Puppet is it?

**Comment by bodgit** [comment]
This isn't my module, you're using the camptocamp one.
